version.tf
Latest Github provider (possibly) crashes due to an update to the latest GO library. Until a fix is in place in the provider, lock the version to the previous (working) version.
**Sources:**
* https://github.com/terraform-providers/terraform-provider-github/pull/342
* https://github.com/google/go-github/pull/1288
=> Lock GitHub version to work around crash

version.tf
Crash has been fixes in latest release. Remove version lock.
Links:
* https://github.com/terraform-providers/terraform-provider-github/blob/master/CHANGELOG.md#250-march-30-2020
* https://github.com/schubergphilis/terraform-github-mcaf-repository/pull/5
=> Remove GitHub version lock

main.tf, variables.tf
Last release of the Github provider added 2 useful features:
- Mark repository as "template" repository
- Set "Delete branch after merging PR" 
Source:
* https://github.com/terraform-providers/terraform-provider-github/blob/master/CHANGELOG.md#260-april-03-2020
* https://www.terraform.io/docs/providers/github/r/repository.html
=> Implement "delete branch on merge" feature

main.tf, variables.tf
The provider now uses a `visibility` attribute to let you choose `public`, `private` or `internal`.
=> Fix deprecation message

main.tf
This way the datasource will wait on the github_repository resource (if any exists) before checking with Github. This way you won't get a 404 when you check a repo that hasn't been created, yet.
=> Data source depends on gitub_repository when created

main.tf, outputs.tf, variables.tf
This variable was added while still using Terraform 0.12 and allowed us to include this module in another module and making creation of a new repo optional as using `count` on a module was not supported.
Since Terraform 0.13 was released we can use `count` on a module and it's better to skip the module completely if the `create_repository` variable is set to `false` in the calling module instead of just the `github_repository` resource, example:
```hcl
module "github_repository" {
count = var.create_repository ? 1 : 0
...
```
Another consideration is a repository should either be managed by this module or not. Currently there is a catch 22 situation where a new repo cannot be created because the `data` resource fails because the repo doesn't exist yet.
=> Drop create_repository variable

README.md, main.tf, variables.tf
Add a `actions_secrets` variables to add support for [Github actions secrets](https://www.terraform.io/docs/providers/github/r/actions_secret.html)
=> Add support for Github Actions secrets

.gitignore, README.md, versions.tf
This PR fixes the following warning:
```│ Warning: Additional provider information from registry
│ 
│ The remote registry returned warnings for registry.terraform.io/hashicorp/github:
│ - For users on Terraform 0.13 or greater, this provider has moved to integrations/github. Please update your source in required_providers.
```
=> Update provider source

main.tf
This resolves issue caused by moving to use the v4 API for this resouce, as part of provider version: 3.1.0
Issue: https://github.com/integrations/terraform-provider-github/issues/908
Provider bump: https://github.com/integrations/terraform-provider-github/pull/337
=> Use repository name as the repository_id for branch protection

README.md, main.tf, variables.tf
Ignore changes to pages property. This way it won't remove otherwise configured pages when using the new GH provider
Related issue that proposes moving it to it's own resource: https://github.com/integrations/terraform-provider-github/issues/782
=> Ignore pages

README.md, main.tf, variables.tf
This still allows you to create additional branches and set another branch as the default branch, but it turns out that nowadays a repo is always initially created with a main branch.
So if you want to use another default branch, you will first need to create it and then update the config to point to the new branch.
This PR enables that again as it turned out this doesn't currently work anymore.
=> Expect the default branch to be "main"

.github/workflows/terraform.yml, README.md, environments.tf, main.tf, variables.tf, versions.tf
This PR introduces support for Github environments allowing to define required reviewers, set branch policies and create environment secrets. Since these resources were only introduced in v4.12.0 of the provider, I've set that as the minimal required version.
=> Add support for Github environments

README.md, main.tf, variables.tf
This PR adds "maintainers" to the repository access configuration. 
See also: 
- https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization
- https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team_repository.html#permission
=> enhancement: Add maintainers

main.tf
This PR refactors the way the teams are configured from index based to key based.
Currenty, changes the teams connected to a repository created a lot of recreates due to the nature of using `count`. By changing it to a `foreach`, only the removed/added/altered team is actually being updated. This because the key in the state file is the team ID (Instead of a "random" index). And minor probably, but also saves a few unneeded API calls to Github
_Note: This will one-time recreate all team permissions settings. This is non-destructive but be aware that this happens_
=> feat: Use foreach for team permissions

README.md, main.tf, variables.tf
Small fix to allow us to specify a branch when using the
`github_repository_file` resource and not be confined to the only the
default branch.
Signed-off-by: Stephen Hoekstra <shoekstra@schubergphilis.com>
=> fix: Support managing files in non-default branches

README.md, main.tf, variables.tf
This PR adds support to configure the Tag Protection.
**Links:**
- https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_tag_protection
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules
=> feature: Add tag protection support

README.md, examples/environments/versions.tf, examples/main-protected/main.tf, examples/main-protected/versions.tf, examples/main-unprotected/versions.tf, examples/master-protected/main.tf, examples/master-protected/versions.tf, examples/master-unprotected/versions.tf, main.tf, variables.tf, versions.tf
**BREAKING CHANGE:**
`push_restrictions` argument is replaced by `restrict_pushes`
(Check https://github.com/integrations/terraform-provider-github/pull/2045 for more details)
Also makes `required_checks` argument actually optional.
=> feat!: Upgrade to GitHub provider v6.0

main.tf
The `restrict_pushes` is defined twice:
`Error: error multiple restrict_pushes declarations`
This PR removes one of the 2
See line 110: https://github.com/schubergphilis/terraform-github-mcaf-repository/pull/66/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbL110
=> bug: remove duplicate restrict_pushes

README.md
This PR corrects the example on how to disable branch protection
=> documentation: Correct use_branch_protection example

README.md, main.tf, variables.tf
This PR adds the configuration of the squash commit message/title. Will be specified when `allow_squash_merge` is true.
Tested this out, and the commit title/message have a default value, so configured this explicitly for simplicity:
```hcl
~ resource "github_repository" "default" {
~ allow_squash_merge          = false -> true
~ squash_merge_commit_message = "COMMIT_MESSAGES" -> "BLANK"
~ squash_merge_commit_title   = "COMMIT_OR_PR_TITLE" -> "PR_TITLE"
}
```
Links:
- https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/
- https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository
=> feat: Add Squash merge commit message/title

README.md, main.tf
This PR refactors the Tag Protection resources.
The old tag protection is deprecated and is replaced with Rulesets:
```Error: POST https://api.github.com/repos/connectedbrewery/nldevoc-sandbox-wspaargaren/tags/protection: 410 This is a scheduled brownout of the tag protections API. Tag protections will be fully deprecated on 2024-08-30. At that point, this API endpoint will be removed. Please use tag rulesets instead. []```
This PR changes the resource from `github_repository_tag_protection` to `github_repository_ruleset` while keeping the functionality intact. The refactor is based on the `export to ruleset` outcome from Github itself:
On purpose made it a 1-on-1 refactor without implementing any specific ruleset features so this can be a patch version. Since it currently is completely …
=> fix: Refactor tag protection resources

README.md, main.tf
This PR fixes the tag protection refactor made in the [previous PR](https://github.com/schubergphilis/terraform-github-mcaf-repository/pull/69).
The pattern is actually just a `condition`, not the name pattern. That is apparantly something else:
So tested a bit more with a test repository and this is the actual configuration to make it work the same as the "old" tag protection regex
=> fix: Fix tag protection refactor

README.md, UPGRADING.md, main.tf, variables.tf
**:hammer_and_wrench: Summary**
Adding some missing functionality
- Added `var.allow_merge_commit` to provide a way to disable merge commits
- Added `var.merge_commit_message` and `var.merge_commit_title` to custom default message and title when using merge commits
- Added `var.allow_update_branch` to provide a way to suggest updating pull request branches
- Added `var.license_template` to provide a way to configure a `LICENSE` file at repository creation time
- Added `var.topics` to set a list of topics on the repository
And changing some default behaviour:
- Make squash merge the only merge strategy out the box: users can set `var.allow_merge_commit` and `var.allow_rebase_merge` to allow all possible merge options
- `var.allow_update_branch` is set to true to present a "update branch" …
=> feat!: Update `github_repository` fields and behaviour

README.md, variables.tf
This pull request updates the default value and description of the `vulnerability_alerts` variable in the `variables.tf` file to improve security and clarity.
**Changes to `variables.tf`:**
* Updated the `vulnerability_alerts` variable:
- Changed the default value from `false` to `true` to enable security alerts for vulnerable dependencies by default.
- Revised the description for better clarity: "Set to true to enable security alerts for vulnerable dependencies."
GitHub enables the alerts on public repos but disables them on private repos by default.
As we often create private repositories inside an organisation, we should default to `true` and let people opt out if they are using a free org or personal namespace.
Signed-off-by: Stephen Hoekstra <shoekstra@schubergphilis.com>
=> fix: Set `var.vulnerability_alerts` default to true

README.md, examples/merge-strategy/main.tf, examples/merge-strategy/terraform.tf, main.tf, tests/basic.tftest.hcl, variables.tf
This pull request introduces a new feature to configure merge strategies for GitHub repositories managed by the module. It adds a `merge_strategy` variable for simplified configuration, updates the default behavior for merge strategies, and includes new tests and examples to validate the functionality.
* Added a new `merge_strategy` variable, allowing users to specify a single merge strategy (`merge`, `rebase`, or `squash`). This variable overrides the individual `allow_merge_commit`, `allow_rebase_merge`, and `allow_squash_merge` settings. Validation ensures only valid values are accepted.
* Updated the logic in `main.tf` to use the `merge_strategy` variable when set, falling back to the individual merge strategy variables otherwise.
* Updated the `README.md` to include instructions for …
=> feat: Add `var.merge_strategy` to select merge strategy
